## To Reproduce The Error

### Step 1: Run quarto through a subprocess

```bash
python run_quarto.py
```

### Step 2: navigate to the /test.html page (which is also on the navbar)

The Error I get:

```
assertion failed [block != nullptr]: BasicBlock requested for unrecognized address
(BuilderBase.h:550 block_for_offset)
/usr/local/bin/quarto: line 145:  9849 Trace/BPT trap: 5       "${QUARTO_DENO}" ${QUARTO_ACTION} ${QUARTO_DENO_OPTIONS} ${QUARTO_DENO_EXTRA_OPTIONS} "${QUARTO_IMPORT_ARGMAP}" "${QUARTO_TARGET}" "$@"
```

## Info about my system:

- OS: MacOS Monterey 12.5.1, Apple M1 Pro
- Quarto Version `1.2.92`

# Observations

- Running `quarto docs` does **not** produce the error
- The error only occurs when I run quarto through a subprocess by running `python run_quarto.py`
- The error only occurs when I navigate to the page generated by the notebook (i.e. `test.html`)
 
